### PR TITLE
Add reacty to the site

### PR DESCRIPTION
**Pull request by solomonshalom**
Added reacty to the site for better engagement and feedback

Check - https://github.com/berrysauce/reacty

### CODE REVIEW

**Comment by zaidajani** [comment]
Hey Solomon,

Your pull request will be merged once you provide a demo of what you did, and as you added reacty to the page, please let us know where the data from reacty will get stored and how to read it. Also, please make sure that reacty shows up only on the word wall page for a better user experience. 

Great idea by the way!

Regards,
Zaid

**Comment by solomonshalom** [comment]
Hey Zaid!

So, the below screenshot shows what it will look like - 
image
In order to read the data, just go to reacty.net and log in with the information I will be giving shortly

With Warm Regards,
Solomon Shalom Lijo

**Comment by zaidajani** [comment]
I'll make an account on reacty and add it to the .env on my local machine and deploy it. Wherever credentials are used, please use process.env.[credential] there so that I can change it while I test it on my local machine.

**Comment by zaidajani** [comment]
Reacty doesn't support react yet, therefore in your way of approach it shows the popup on all of the pages. As mentioned earlier, we want the popup in just one route or component. We therefore cannot accept your pull request, but still thanks for your efforts.

**Pull request closed without merging**
